[package]
name = "recordbox"
version = "0.1.0"
edition = "2024"
description = "A fluent music library manager"

[dependencies]
axum = { version = "0.8.8", default-features = false, features = ["http2", "tokio", "json"] }
config = { version = "0.15.19", features = ["yaml"] }
mp4ameta = "0.13.0"
musicbrainz_rs = "0.12.0"
reqwest = { version = "0.13.1", default-features = false, features = ["charset", "default-tls", "http2", "gzip", "json", "query"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", default-features = false, features = ["macros", "rt-multi-thread"] }
